### ISSUE TITLE
[microk8s] helm install devspace-cloud not working

### ISSUE THREAD

**Issue by hitman249** [devspace-sh/devspace#1104]
**What happened?**
Incorrect devspace installation
No certificate issued

**How can we reproduce the bug?**
Used microk8s

1. 

```
microk8s.kubectl create namespace devspace-cloud
microk8s.kubectl config view --raw > ~/.kube/config
```

1. 

```
microk8s.helm3 install devspace-cloud devspace-cloud --repo https://charts.devspace.sh/ \
  --namespace devspace-cloud \
  --set database.password=secret \
  --set ingress.enabled=true \
  --set ingress.tls.enabled=true \
  --set ingress.domains={devspace.my-domain.tld} \
  --wait
```

```
Error: timed out waiting for the condition
```

1. Connect in dev

   ```
   # devspace create space test               
   [fatal]  get projects: get token: token request: Get https://devspace.my-domain.tld/auth/token?key=918cf6da6c89444b4d8d7348fd4888d2: x509: certificate is valid for ingress.local, not devspace.my-domain.tld
   ```

**Local Environment:**

* DevSpace Version: 4.12.3
* Operating System: linux (ubuntu server 20.04)
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: DevSpace Cloud
* Kubernetes Version: 1.18.2-41+b5cdb79a4060a3

**Anything else we need to know?**
Page correct opens
[https://devspace.my-domain.tld](https://devspace.my-domain.tld)

/kind bug

**Comment by LukasGentele** [comment]
@hitman249 Thanks for opening this issue. If you are running microk8s, you should not use `--set ingress.tls.enabled=true`. Instead, use `false`. TLS will not be required if DevSpace Cloud runs on your machine. The helm deployment seems to be timing out but that can have many reasons. Check the deployments/replicasets/pods using `kubectl get/describe deploy/replicaset/pod` and try to identify why devspace cloud cannot start in your microk8s cluster.

**Comment by hitman249** [comment]
@LukasGentele Thanks for the answer, but `devspace` requires ssl
```bash
$ devspace login  
[info]   If the browser does not open automatically, please navigate to https://devspace.my-domain.tld/login?cli=true
```

**Comment by LukasGentele** [comment]
@hitman249 That is indeed the default option but you can run `devspace add provider PROVIDER_NAME --host=http://DOMAIN.TLD` to specify an insecure connection via http.
