### ISSUE TITLE
ContainerPath on Windows pod

### ISSUE THREAD

**Issue by zohaibhafeez** [devspace-sh/devspace#1206]
**What happened?**
Trying to configure sync for a Windows pod but devspace dev gets stuck on "Starting Sync.."

**What did you expect to happen instead?**
localSubPath folder should sync with the ContainerPath defined in the Windows pod.

**How can we reproduce the bug?** (as minimally and precisely as possible)
dev:
sync:

* labelSelector:
  app: api
  localSubPath: ./WebApi
  containerPath: "C:/webApp"

Tried the following in ContainerPath:
c:\\webApp
c:\\webApp
\\c:\\webApp
webApp
./
I also tried by removing the ContainerPath settings but no luck.

**Local Environment:**

* DevSpace Version: 5.2.0
* Operating System: windows
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Kubernetes Version: \[1.18.8\]

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@zohaibhafeez thanks for reporting this issue! Currently syncing windows containers is not supported since the helper binary is compiled for linux containers and cannot be executed on windows for now.

**Comment by dahovey** [comment]
@FabianKramm Are there any updates on this? I have several projects that require Windows containers and would like to use devspace and file syncing from local dev machine. Right now I get error `start_dev: start sync: error executing tar: tar: Error opening archive: Failed to open '\\.\tape0'`

![image](https://github.com/devspace-sh/devspace/assets/22330242/39437d0d-e303-4d51-87fc-06a7d8e73fc4)
