### ISSUE TITLE
no sub command `available-components` for `list` operation

### ISSUE THREAD

**Issue by vorti2** [devspace-sh/devspace#1315]
**What happened?**
If I go to load a default deployment via

```
devspace add deployment database --component=mysql
```

following output was written:

```
[fatal]  Please specifiy one of these parameters:
--image: A docker image to deploy (e.g. dscr.io/myuser/myrepo or dockeruser/repo:0.1 or mysql:latest)
--manifests: The kubernetes manifests to deploy (glob pattern are allowed, comma separated, e.g. manifests/** or kube/pod.yaml)
--chart: A helm chart to deploy (e.g. ./chart or stable/mysql)
--component: A predefined component to use (run `devspace list available-components` to see all available components)
```

If I enter `devspace list available-components` devspace replies  list of commands for the `list` operation, but no `available-components`.

**What did you expect to happen instead?**
Specify the correct help page or disable the loading ability for default components.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Do `devspace add deployment database --component=mysql` in the actual version.

**Local Environment:**

* DevSpace Version: devspace version 5.7.5
* Operating System: mac
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: minikube
* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@vorti2 thanks for opening this issue! The command `devspace list available-components` was removed some time ago, seems like the reference there needs to be deleted as well. We removed the command, became a burden for us to maintain these applications and we think it is usually better to deploy an official helm chart that is much more powerful and more up-to-date. You can browse these at https://artifacthub.io/

**Comment by vorti2** [comment]
👍 and always super responsive 👏

**Comment by deniseschannon** [comment]
Closing as it looks as if it was resolved.
