### ISSUE TITLE
Enable specific version for devspace upgrade

### ISSUE THREAD

**Issue by Chrislevi** [devspace-sh/devspace#1330]
**Is your feature request related to a problem?**
Lately, the Loft team introduced some new versions with breaking changes on our side due to us leveraging generated.yaml as a file. Due to this issue until we fix it on our side we still want to use an older version. but intuitively our developers are upgrading to latest devspace version whenever there is a new one.

**Which solution do you suggest?**
Add version arg for devspace upgrade command

**Which alternative solutions exist?**
Manually download Devspace older version from Github releases

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@Chrislevi thanks for creating this issue! Yes we can add that, this is also useful if you would want to use a beta prerelease for example

**Comment by Chrislevi** [comment]
Exactly! thanks for the fast development, I can see its part of 5.8.2 prerelease :)
