### ISSUE TITLE
helm2 is using user helm cache direction

### ISSUE THREAD

**Issue by chasebolt** [devspace-sh/devspace#1355]
**What happened?**
helm2 is using my broken user's `~/.helm` directory

**What did you expect to happen instead?**
devspace to specify `--home` in its helm2 and use its own cache

**How can we reproduce the bug?** (as minimally and precisely as possible)
break your helm2 somehow. unfortunately I cant give instructions here, but my `~/.helm` was busted and helm2 from devspace was failing to deploy. it took a long while to sort that problem out as I did not expect devspace to be using my local helm cache. delete my local helm cache allowed devspace to function and deploy again.

**Local Environment:**

* DevSpace Version: 5.9.1
* Operating System: linux
* Deployment method: helm

**Anything else we need to know?**
Would also set the equivalent flag for helm3

/kind bug

**Comment by FabianKramm** [comment]
@chasebolt thanks for creating this issue! I'm not sure if we should do that, if the users helm cache is not broken it usually has quite some advantages to use a single cache on the computer. Did you try to use `upgradeArgs` and `fetchArgs` to change the home directory via helm? This probably would also solve your problem.

**Comment by chasebolt** [comment]
Nope. This user didn't have helm installed at the time of me debugging this. At some point they obviously did have helm, busted their setup, and removed it, but left over the helm cache directory.

From my perspective (as someone who is supporting different skill levels of developers with devspace) I would want devspace to be isolating its helm cache and config.

Feel free to close this though 😃
