### ISSUE TITLE
Ability to define hostPath volume with the Component Chart

### ISSUE THREAD

**Issue by saruman9** [devspace-sh/devspace#1364]
**Is your feature request related to a problem?**
Yes. I should use a k8s manifest file for using `hostPath` volume, but it would be nice if I could use the Component Chart for all deployments.

**Which solution do you suggest?**
Add ability to define `hostPath` volume with the Component Chart.

**Which alternative solutions exist?**
Use a k8s manifest file.

/kind feature

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! Yes I guess in future we could allow that

**Comment by MathiasVandePol** [comment]
@lizardruss @FabianKramm I made a PR here which allows for that: https://github.com/loft-sh/component-chart/pull/85
