### ISSUE TITLE
CrashLoopBackOff when execute devspace dev

### ISSUE THREAD

**Issue by NaufalRE** [devspace-sh/devspace#1436]
I really excited to hear there is an automation deployment !

1. I tried to deploy a clean laravel project, I doing same as [documentation laravel deployment](https://devspace.cloud/blog/2019/10/16/deploy-laravel-to-kubernetes)
   but i change the folder owner (sudo chown -R $USER laravel-project) because when i tried to write something it got access denied
2. The first initialization I prefer using : helm: Use Component Helm Chart \[QUICK START\]
3. and then Create a new Dockerfile for this project
4. Choose PHP as programming language
5. Use [hub.docker.com](http://hub.docker.com)
6. and then i use 8080 port as port forwarding
7. after waiting a couple of minutes, it returning an error :
   Pod naufalre/re-kube-7dbc8c75c5-5hgcr-devspace has critical status: CrashLoopBackOff. DevSpace will continue waiting, but this operation might timeout

thank you, i really appreciate it

devspace version 5.12.2
OS : running under WSL 2

**Comment by FabianKramm** [comment]
@NaufalRE thanks for creating this issue and sorry for the delay. It seems like the tutorial is not up to date anymore, we'll have to update that.

**Comment by NaufalRE** [comment]
> @NaufalRE thanks for creating this issue and sorry for the delay. It seems like the tutorial is not up to date anymore, we'll have to update that.

It's okay, i really appreciate you guys doing out there. I really interested to learn devspace deployment
