### ISSUE TITLE
after "docker system prune" devspace can not find the image, a check if image exists and if not building it good be good

### ISSUE THREAD

**Issue by leventogut** [devspace-sh/devspace#1447]
**What happened?**

after "docker system prune" devspace can not find the image, a check if image exists and if not building it  good be good

**What did you expect to happen instead?**
rebuild imahge

**How can we reproduce the bug?** (as minimally and precisely as possible)
devspace dev/deploy
docker system prune
devspace dev/deploy

**Local Environment:**

* DevSpace Version: 5.13.0
* Operating System:  | mac
* Deployment method: helm |

**Kubernetes Cluster:**

* Cloud Provider: docker-desktop
* Kubernetes Version: \[use `kubectl version`\]
  Client Version: [version.Info](http://version.Info){Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: [version.Info](http://version.Info){Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  **Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@leventogut thanks for creating this issue! Yes this is a known issue for local kubernetes cluster where you don't push the image. We can think about making an extra check for this case.
