### ISSUE TITLE
devx: Warn when the `values` field incorrectly contain dots

### ISSUE THREAD

**Issue by arcanis** [devspace-sh/devspace#1476]
**Is your feature request related to a problem?**

I was installing the following chart:
[https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/)

As you can see, it requires setting a few parameters:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/bfaf7b10-9700-4653-ac43-c5c0e764e106/ed37d04f-1eb6-4166-b011-ce5f465a04e5)

Naturally, that's what I did in my `devspace.yaml`:

```
values:
  auth.username: foo
  auth.password: bar
```

And I spent two evenings trying to figure out why the hell I couldn't connect to the instance, and thinking it was due to some lingering Helm cache somewhere, deleting and recreating everything I could, when the problem simply was that the syntax was incorrect (which I noticed by printing the content of the `values.yml` file you generate, and comparing with the [bitnami defaults](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L61-L65)).

**Which solution do you suggest?**

One of those two:

* Either crash if a top-level property in `values` contain a dot
* Or silently transform it into an object

/kind feature

**Comment by FabianKramm** [comment]
@arcanis thanks for creating this issue! I agree that can be quite confusing, we could add a warning if something like this is encountered during deploy to notify the user of a potential mistake, but crashing or converting the dots automatically is probably not something we want, as it is possible in the `values.yaml` of helm itself to define such constructs (although very very rare I agree). Hence it would limit expressibility and if a chart would use such a construct it would be incompatible with DevSpace.
