### ISSUE TITLE
Helm downloaded by devspace was for x86_64 on Apple M1 ( Guest OS: Ubuntu ARM64 VM, host: macOS Apple M1)

### ISSUE THREAD

**Issue by wxw-matt** [devspace-sh/devspace#1494]
**What happened?**
Helm downloaded by devspace was for  x86_64 on Apple M1 ( Ubuntu ARM64 VM )
File location: /home/wxw/.devspace/bin/helm
**What did you expect to happen instead?**
It should download an ARM64 version.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Running an Ubuntu ARM64 VM and install devspace inside it.

**Local Environment:**

* DevSpace Version: 5.14.3
* Operating System: Guest OS: Ubuntu ARM64 VM, host: macOS Apple M1
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: minikube
* Kubernetes Version: v1.20.7

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@wxw-matt thanks for creating this issue! Thanks for the PR #1495 , this should be fixed now, correct?

**Comment by wxw-matt** [comment]
Yeah, it works now. Thanks for merging the PR.
