### ISSUE TITLE
devspace pod reset

### ISSUE THREAD

**Issue by sczhh** [devspace-sh/devspace#1503]
If my devspace.yaml file is missing, how do I reset the Pod, and can I provide an automatic Pod reset function?

**Comment by FabianKramm** [comment]
@sczhh thanks for creating this issue! If your devspace.yaml is missing, you can reset your deployments via `kubectl`:

```
# Delete the replaced pods
kubectl delete po -n my-namespace --selector devspace.sh/replaced=true

# Scale up the deployment
kubectl scale deployment.v1.apps/my-deployment -n my-namespace --replicas=1
```

**Comment by LukasGentele** [comment]
Instead of `true`, why don't we save the deployment or statefulset name in the annotation and make the reset function work even without the config?
