### ISSUE TITLE
Default profile for `devspace dev`

### ISSUE THREAD

**Issue by nVitius** [devspace-sh/devspace#1507]
**Is your feature request related to a problem?**
I've been using `dev.replacePods` to add local env variables to my containers.
My only issue with this approach is that it scales the deployment down to 0 and creates a pod outside of it. This makes it a bit difficult to restart these pods when needed.

Instead, I would like to define a profile called `dev` and use the `profile.patches` to add my env variables this way instead.

**Which solution do you suggest?**
It would be great to have a `dev.profile` property where you could set a default profile when running `devspace dev`

**Which alternative solutions exist?**
This is already possible by specifying the profile explicitly in the command (e.g. `devspace dev -p dev`).
This wouldn't be an issue, but I can see it being annoying if you forget to add the profile or perhaps it isn't communicated that it is necessary.

**Additional context**
I'd be glad to work on this if someone would point me in the right direction. I haven't worked with Golang before and am having a hard time understanding where everything is in the codebase.

/kind feature

**Comment by FabianKramm** [comment]
@nVitius thanks for creating this issue! Did you try to use the `devspace use profile` command which sets a default profile? That should be very similar to what you want to achieve.

**Comment by lizardruss** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
