### ISSUE TITLE
If a "var" is set as password it should be masked on outputs and logs

### ISSUE THREAD

**Issue by leventogut** [devspace-sh/devspace#1513]
vars:

* name: DB_PASSWORD
  password: true
* name: DB_ROOT_PASSWORD
  password: true

LOGS>>
info\]   Execute hook 'sh -c while ! mysql -u root -p"db.root.password/" -e ";" >/dev/null 2>&1 ; do
echo "Waiting for database to be ready...";
sleep 3;
done

echo "CREATE USER IF NOT EXISTS 'laravel'@'%' IDENTIFIED BY 'db.password'; ALTER USER 'laravel' IDENTIFIED BY 'db.password';" | mysql -u root -p'db.root.password/'
'
\[info\]   Waiting for running containers for hook 'sh -c while ! mysql -u root -p"db.root.password/" -e ";" >/dev/null 2>&1 ; do
echo "Waiting for database to be ready...";
sleep 3;
done

echo "CREATE USER IF NOT EXISTS 'laravel'@'%' IDENTIFIED BY 'db.password'; ALTER USER 'laravel' IDENTIFIED BY 'db.password';" | mysql -u root -p'db.root.password/'
'
\[info\]   Execute hook 'sh -c while ! mysql -u root -p"db.root.password/" -e ";" >/dev/null 2>&1 ; do
echo "Waiting for database to be ready...";
sleep 3;
done

echo "CREATE USER IF NOT EXISTS 'laravel'@'%' IDENTIFIED BY 'db.password'; ALTER USER 'laravel' IDENTIFIED BY 'db.password';" | mysql -u root -p'db.root.password/'

**Comment by FabianKramm** [comment]
@leventogut thanks for creating this issue! Yes makes sense, I think we can add this

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
