### ISSUE TITLE
use .gitignore as the exclude sync files

### ISSUE THREAD

**Issue by DanArlowski** [devspace-sh/devspace#1562]
**Is your feature request related to a problem?**
As we use many files and folders in the repo , and every use may have a bit different folder configs, some folders named differently, etc , the gitignore is the most updated file to make sure nothing gets pushed to the repo

**Which solution do you suggest?**
Allow the abillity to state devspace config to use .gitignore as the exclusion list

**Which alternative solutions exist?**
Copy paste by hand, managing 2 different list and keeping them in sync

**Additional context**
May be great feature for complex git repos.

/kind feature

**Comment by FabianKramm** [comment]
@DanArlowski thanks for creating this issue! Yes, I see your point, but I believe this does not always work, however we might want to add an option to load the exclude paths from file, where you could just specify the `.gitignore` file

**Comment by DanArlowski** [comment]
I agree that adding a file may work great,
Then we can add any file and .gitignore as one of them. 

This is a feature I will gladly appreciate.
