### ISSUE TITLE
Cannot access the UI from within a Github Codespace

### ISSUE THREAD

**Issue by arcanis** [devspace-sh/devspace#1574]
**What happened?**

The [Codespaces](https://github.com/features/codespaces) expose their ports through https. Since the UI loads its config through HTTP, Chrome rejects the request:

> Mixed Content: The page at '[https://xxxx.githubpreview.dev/](https://xxxx.githubpreview.dev/)' was loaded over HTTPS, but requested an insecure resource '[http://xxxx.githubpreview.dev/api/config](http://xxxx.githubpreview.dev/api/config)'. This request has been blocked; the content must be served over HTTPS.

The fix would be to use the same protocol when loading the config as the one used when accessing the UI.

**What did you expect to happen instead?**

Should work! 🙂

**How can we reproduce the bug?** (as minimally and precisely as possible)

Will need a Codespace beta access, but you can probably test it more easily by using some kind of https proxy.

**Local Environment:**
Latest DevSpace release

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@arcanis thanks for creating this issue! Yes the http is currently hardcoded, but we can easily make that dynamic, thanks for pointing that out!

**Comment by FabianKramm** [comment]
@arcanis we just released v5.15.0-beta.0, would be great if you could confirm that this fixes your problem
