### ISSUE TITLE
Files not deleted using mirrorLocal inital sync

### ISSUE THREAD

**Issue by kickthemooon** [devspace-sh/devspace#1578]
**What happened?**
Using mirrorLocal (default) initial sync, files, which are locally non-existent, were not deleted from remote because that directory was specified in the downloadExcludePaths.

**What did you expect to happen instead?**
That, if mirrorLocal is used, those files will be deleted because they are not specified in the list of uploadExcludePaths

**How can we reproduce the bug?** (as minimally and precisely as possible)
use mirrorLocal initial sync strategy
have a directory on remote as well as locally present
have a file in that directory on remote which is not present locally
add the directory path to downloadExcludePaths
start devspace sync

**Local Environment:**

* DevSpace Version: latest
* Operating System: mac

**Kubernetes Cluster:**

* Cloud Provider: aws
* Kubernetes Version: 14

**Anything else we need to know?**
After I remove the directory from downloadExcludePaths the files get deleted which are not present locally

/kind bug

**Comment by FabianKramm** [comment]
@kickthemooon thanks for creating this issue! Yes you are correct, we should change this.

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
