### ISSUE TITLE
devspace open fails to open port-forward to services with named ports

### ISSUE THREAD

**Issue by nevalla** [devspace-sh/devspace#1613]
**What happened?**
When trying to open port-forward with `devspace open`, devspace fails to open port-forward to services that are using named ports.

```
? Select the service you want to open:  [Use arrows to move, type to filter]
  nginx-ingess-nginx-ingress-controller:0
  nginx-ingess-nginx-ingress-controller:0
> nginx-ingess-nginx-ingress-controller-default-backend:0
  postgres-postgresql:0
  redis-master:0
```

port definition for `nginx-ingress-nginx-ingress-controller`:

```
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
```

**What did you expect to happen instead?**
Devspace allows to open port-forward also to named ports. Kubectl already supports this:

`kubectl port-forward services/nginx-ingess-nginx-ingress-controller 8080:http`

**How can we reproduce the bug?** (as minimally and precisely as possible)
Install nginx helm chart and try to open port-forward with `devspace open` command.

/kind bug

**Comment by FabianKramm** [comment]
@nevalla thanks a lot for creating this issue! Yes you are correct, seems like this is a bug

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
