### ISSUE TITLE
Allow devspace analyze to only report on pods created from devspace.yaml

### ISSUE THREAD

**Issue by nachin** [devspace-sh/devspace#1729]
**Is your feature request related to a problem?**
We currently generate preview environments for prs in the same namespace. We would like to be able to run `devspace analyze` when a deployment fails to help in debugging. Since analyze can only be scoped down to a namespace we are getting the report for all resources in the namespace and not just the deployment(s) we are interested in.

**Which solution do you suggest?**
Have a flag that allows` devspace analyze` to scan only resources that would be generated from the `devspace.yaml`.

**Which alternative solutions exist?**

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@nachin thanks for creating this issue! Yes we could add a flag for this

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
