### ISSUE TITLE
"No images to rebuild" message

### ISSUE THREAD

**Issue by stickeegreg** [devspace-sh/devspace#1852]
If you follow the quickstart guide then run `devspace build` you are given the message `[info]   No images to rebuild. Run with -b to force rebuilding`. Adding the `-b` flag simply gives the same result.

```
git clone https://github.com/loft-sh/devspace-quickstart-php
cd devspace-quickstart-php
devspace init
devspace use namespace my-namespace  
devspace build -b

[info]   No images to rebuild. Run with -b to force rebuilding
```

**Is your feature request related to a problem?**
No

**Which solution do you suggest?**
The devspace.yaml file doesn't define any images for the default build, so a better error message would be:

`[info] No images defined for this profile`

/kind feature

**Comment by FabianKramm** [comment]
@stickeegreg thanks for creating this issue! Yes we should change that, good catch!

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
