### ISSUE TITLE
Add `description` and `hidden` field to profiles

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [devspace-sh/devspace#1909]
Currently, we construct a devspace yaml file by having the default `dev` profile simply define an empty structure, and then all other profiles patch it. Some profiles are building block profiles, others are "public" profiles. This request is for two features:

* Add an optional `hidden` field to profiles. This would make it so that they do not show up under `devspace list profiles`. Currently, we use a leading underscore in the profile name to separate "public" from "private" profiles. Alternatively, do not list profiles with a leading underscore in the name. "hidden" profiles would still be usable as parent profiles, even across projects.
* Add an optional `description` field to profiles. This could show up when you list profiles so that people have a better understanding on how to use the profile and what it is doing.

**Comment by FabianKramm** [comment]
@JamesHutchisonCarta thanks for creating this issue! That makes a lot of sense, I agree that we should add this.

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
