### ISSUE TITLE
Path broken for custom commands after 5.18.0

### ISSUE THREAD

**Issue by mykiep** [devspace-sh/devspace#1918]
**What happened?**
Custom commands that were working in 5.17.0 stopped working after upgrading to 5.18.0+.

**What did you expect to happen instead?**
The Path should be loaded and npm commands should execute

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
- name: "test-path"
  command: "npm -v"
...
```

## Devspace version 5.17.0 worked fine

```
C:\test>devspace -v
devspace version 5.17.0
C:\test>devspace run test-path
6.14.16
```

## When upgrading to any version after 5.18.0, it stops working

```
C:\test>devspace upgrade
[done] √ Successfully updated to version 5.18.4
[info]   Release note:
...
C:\test>devspace -v
devspace version 5.18.4
C:\test>devspace run test-path
'npm' is not recognized as an internal or external command,
operable program or batch file.
```

**Local Environment:**

* DevSpace Version: 5.18.0 - 5.18.4
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: aws
* Kubernetes Version: 1.22.2

**Anything else we need to know?**
I believe that this is a path issue as when I print the path variable in a command, it is separated by ":" instead of ";".  I tested this by updated the command to "echo $Path"

/kind bug

**Comment by FabianKramm** [comment]
@mykiep thanks for reporting this issue! We'll take a look!

**Comment by Quasarman** [comment]
Hello I am facing the same issue. Just upgraded from 5.17.0 to 5.18.5 and got an error:

```
'.' is not recognized as an internal or external command, operable program or batch file
```

The odd thing is that I am not even calling an executable but just providing a path to a build script like stated in the docs.

```
images:
...
  custom:
    command: ./scripts/run-build.bat
```

I have also tried running inside a powershell and gitbash, with and without the trailing `./` and also using  `commands` and providing `os: windows`. Same result every time.

The scripts folder is on the same level as the devspace.yaml file.

**Comment by FabianKramm** [comment]
@Quasarman @mykiep does this problem still occur on DevSpace v6?

**Comment by Quasarman** [comment]
@FabianKramm 

I cant really tell since we switched from using gradle to just using devspace. That said we haven't had tine to upgrade to v6 yet.

**Comment by mykiep** [comment]
I haven't been able to try devspace 6+ since kaniko support for building in a remote kubernetes cluster seems to be broken.  I haven't been able to submit a ticket for that yet.

**Comment by mykiep** [comment]
I created ticket #2412 for the devspace 6 issue.
