### ISSUE TITLE
Stream all pod logs in v6 running devspace dev

### ISSUE THREAD

**Issue by blaisertm** [devspace-sh/devspace#2304]
**Is your feature request related to a problem?**

Not really, just inconvenient. In v6 it only streams the first pod's logs that matches the selector(s). In v5 it streams all matching pods' logs.

**Which solution do you suggest?**

Behaviour seen in v5.

**Which alternative solutions exist?**

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@blaisertm thanks for reporting this! I'm thing about adding support to target all pods that match a selector to the dev config, so that syncing to multiple pods would work as well. We'll see how much effort that would be.
