### ISSUE TITLE
`devspace purge` doesn't do anything

### ISSUE THREAD

**Issue by fuhengwu2021** [devspace-sh/devspace#2341]
**What happened?**

I was using `devspace` for docker image deployment. But it hang there forever due to ImagePullBackOff. Then I use `ctrl-c` to exit devspace from forever waiting.

Then I tried to run `devspace purge` it doesn't do anything. Some resources were already created in k8s. If I run `devspace deploy` it will fail immediately because the resource already exists.

**What did you expect to happen instead?**

devspace should handle exceptions gracefully.

**How can we reproduce the bug?** (as minimally and precisely as possible)

run devspace deploy and then ctrl-c, then run devspace deploy again. It always fails.

/kind bug

**Comment by fuhengwu2021** [comment]
my terminal was shutdown due to network issue, and I ran `devspace purge`, then I got:

```
stop_dev: couldn't execute 'devspace purge', because there is another DevSpace session for the project (xxx) already running inside this namespace

...

fatal exit status 1
```

**Comment by FabianKramm** [comment]
Hello @fuhengwu2021 ! Thanks for creating this issue! Are you absolutely sure there was no other DevSpace process running in this namespace while you were trying to purge it?

**Comment by alexandradragodan** [comment]
Hello, @fuhengwu2021 !
Thanks again for reporting this issue.  

Could you please help us investigate that by checking if the namespace you were describing had any other DevSpace process running while you were trying to purge it? If you need help checking that, we'd be happy to support!

Thank you for your kind help!

**Comment by ADustyOldMuffin** [comment]
I'm not the above user, and their issue sounds like an extra devspace running but I am having this issue.

I'm calling `purge_deployments my-deployment` and it exits fine, but nothing happens. I can run helm list and still see the deployment. I do note that running it with debug it says it's excluded a project, but when I run with `--force-purge` it still doesn't respect this.

**Comment by andrebong** [comment]
yeah same here

**Comment by lizardruss** [comment]
@ADustyOldMuffin @andrebong

I think what is happening is that `purge_deployments my-deployment` will only delete the original deployment, but leave the "replace pods" deployment in place.

You can try running `devspace reset pods` and this should delete the "replace pods" deployment as well. If you'd like to make it part of your pipeline, modify `devspace.yaml` to include a call to `stop_dev my-deployment`

```yaml
pipelines:
  purge-test: |-
    stop_dev my-deployment
    purge_deployments my-deployment
```
