### ISSUE TITLE
Imported profiles are not displayed when running `list profiles`

### ISSUE THREAD

**Issue by alexissellier** [devspace-sh/devspace#2439]
When running the command `devspace list profiles`, the profiles imported by the section  `imports` are not listed.

**What happened?**

```
$ devspace list profiles
  
            NAME         | DESCRIPTION  
  -----------------------+--------------
    profile_not_imported |        
```

**What did you expect to happen instead?**

```
$ devspace list profiles
  
            NAME         | DESCRIPTION  
  -----------------------+--------------
    profile_not_imported |
    imported_profile |    
```

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: devenv

imports:
  - path: ./profile.yaml

profiles:
  - name: profile_not_imported
```

profile.yaml:

```
version: v2beta1
name: devenv

profiles:
  - name: imported_profile
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: linux
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: local with kind
* Kubernetes Version: v1.25.2

**Anything else we need to know?**

**Comment by pratikjagrut** [comment]
@alexissellier Thank you for crating this issue. We'll look into it.

**Comment by fsniper** [comment]
This is something I am also hitting with 6.3.15 version.

**Comment by willysamz** [comment]
I'm also running into this problem. Although the imported profile seems to actually work when used with `-p`. `devspace list profiles` does not list the profiles. Currently using version 6.3.18. Are there any suggestions?
