### ISSUE TITLE
ssh to containers enabled for ssh stopped working between 6.1.1 and 6.2.1

### ISSUE THREAD

**Issue by shearic** [devspace-sh/devspace#2451]
after updating devspace from 6.1.1 to 6.2.1 I get errors trying to ssh into the containers that I have enabled for ssh access.

It looks like there are a few ways it fails.

From a container that gets no errors with `devspace dev --debug`:

```
$ ssh nginx.server.devspace
Warning: Permanently added '[localhost]:10400' (ECDSA) to the list of known hosts.
richshea@localhost: Permission denied (publickey).
```

Another container that gets the following errors with `devspace dev --debug`:

```
18:28:32 dev:phoenix term  Error installing screen: /usr/bin/apt-get
Couldn't find screen, need to fallback.
 W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
 command terminated with exit code 1
```

fails this way:

```
$ ssh phoenix.server.devspace
devspace@localhost: Permission denied (publickey).
```

Another container that sees the following errors:

```
18:28:27 dev:database ssh   Inject devspacehelper...
18:28:27 dev:database ssh   Couldn't find devspacehelper, will try to download it now
18:28:29 dev:database ssh   Successfully injected devspacehelper into pod devlocal/database-postgresql-0
18:28:29 dev:database ssh   Use 'ssh database.server.devspace' to connect via SSH
18:28:29 dev:database ssh   qemu: uncaught target signal 11 (Segmentation fault) - core dumped
18:28:31 dev:database ssh   restarting ssh process because: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
 command terminated with exit code 139
18:28:31 dev:database ssh   qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

fails this way:

```
$ ssh database.server.devspace
kex_exchange_identification: Connection closed by remote host
Connection closed by ::1 port 10951
```

**Comment by pratikjagrut** [comment]
Hey, @shearic Thanks for creating this issue. We'll look into it and we'll fix it asap.

**Comment by pratikjagrut** [comment]
What system are you using?

**Comment by pratikjagrut** [comment]
> ```
> 18:28:32 dev:phoenix term  Error installing screen: /usr/bin/apt-get
> Couldn't find screen, need to fallback.
>  W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
> E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
> E: Unable to lock directory /var/lib/apt/lists/
>  command terminated with exit code 1
> ```

Do you have root permission in the container? This seems to be a root privilege issue.

**Comment by shearic** [comment]
for that phoenix container it definitely doesn't have root access (but it did work in 6.1.1).

the "database" container is also not root, and is this one:
```
      chart:
        name: postgresql
        version: "11.9.11"  # pinned chart 11.9.11 brings in postgres 14.5
        repo: https://charts.bitnami.com/bitnami/
```

the nginx container does have root and is based on `nginx:1.21.0`.

**Comment by lizardruss** [comment]
For this error, it seems to be an issue with the image and ARM emulation mac. 
>18:28:31 dev:database ssh   restarting ssh process because: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
 command terminated with exit code 139
 
 This isn't under our control, but the workaround is to use the upstream image by setting some helm chart values
 ```yaml
 deployments:
   database:
     helm:
       chart:
         name: postgresql
         version: "11.9.11"  # pinned chart 11.9.11 brings in postgres 14.5
         repo: https://charts.bitnami.com/bitnami/
       values:
         image:
           repository: postgres
           tag: '14.5'
 ```

**Comment by lizardruss** [comment]
@shearic Is this issue is still occurring, please re-open the issue and we'll take another look. Thanks!
