### ISSUE TITLE
[Feature Request] File Upload Progress

### ISSUE THREAD

**Issue by karbowiak** [devspace-sh/devspace#2496]
Hi there, atm devspace just lists..

```
build:web Uploading files to build container...
```

And you're just kinda sitting there waiting for it to finish, would it be possible to add a progress bar to it ? (Even if the total size isn't known, at least showing how fast it's uploading should give the user an idea of something happening)

**Comment by FabianKramm** [comment]
Hey @karbowiak ! Thanks for creating this issue, yes that sounds like a good idea!

**Comment by alexandradragodan** [comment]
Hey, @karbowiak 👋 

Our colleague, @89luca89 , is already working on it. 🚀 

Keep you posted when that's merged.

**Comment by karbowiak** [comment]
Awesome! thanks @alexandradragodan 😄

**Comment by zrks** [comment]
Hi, launched with these parameters, but no progress bar at all:
```bash
            "--debug", "sync",
            "--container", "<container_name>",
            "--image-selector", "<image_name>",
            "--label-selector", "<label_selector>",
            "--path", "<path>",
            "--kubeconfig", "<config>",
            "--namespace", target,
```
`DevSpace version : 6.3.1`

How to get one to display?
