### ISSUE TITLE
Helm dependency update not working anymore on 6.2.4 and 6.2.5

### ISSUE THREAD

**Issue by tobalsgithub** [devspace-sh/devspace#2523]
**What happened?**
Our helm dependencies are no longer getting updated appropriately on version 6.2.4 and 6.2.5. 6.2.3 works fine.

We think this is related to the change introduced [here](https://github.com/devspace-sh/devspace/pull/2490).

For some context, our directory structure looks something like this:

```
./devspace.yaml
./helm/
./helm/<chart-name>/
./helm/<chart-name>/Chart.yaml
./helm/<chart-name>/<all other helm related files are in this folder>
```

On version 6.2.3, when we run `devspace dev`, it appropriately runs the `helm dependency update` command, and we see a `charts` folder with our dependencies show up in `helm/<chart-name>/charts`.

But on version 6.2.4 and 6.2.5, we see the following error:

```
deploy:test Deploying chart  (test) with helm...
create_deployments: error deploying test: unable to deploy helm chart: Release "<redacted>" does not exist. Installing it now.
 error executing 'helm upgrade <redacted> --values /var/folders/jy/fpvqp56d3_s3v83dzs6vhxp80000gp/T/3112120045 --install --namespace <redacted> /Users/<redacted>/<redacted>/helm/<chart-name> --wait --timeout=300s --kube-context <redacted>: Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: <name of chart dependency>

fatal exit status 1
```

If we manually run `helm dependency build` inside the `helm/<chart-name>` folder, we see all the appropriate dependencies show up, and subsequent runs of `devspace dev` work great. So we have a workaround, but something definitely broke here at least for us and our folder structure.

**Comment by 89luca89** [comment]
Thanks @tobalsgithub , we will take a look at it :+1:

**Comment by lizardruss** [comment]
@tobalsgithub Could you try something for me?
- Add the following `upgradeArgs` to your deployment config for your deployments:
  ```yaml
  deployments:
    test:
      helm:
        # other config same as before
        upgradeArgs:
          --dependency-update
  ```
- Clear the `charts` directory and maybe also `Chart.lock`
- Run `devspace dev` again

If that clears up the issue we can refactor DevSpace to add that flag.

**Comment by tobalsgithub** [comment]
@lizardruss this worked beautifully, and is very easy for us to implement. 

Are you expecting to make a change that would remove the need for this flag? It's really no pain at all for us to have it. And maybe some use cases don't want the flag, so perhaps this is actually the way we want it?

**Comment by lizardruss** [comment]
@tobalsgithub Great! Thanks for trying that out. I've created PR #2545 to use that flag instead.

I have doubts that it would work for your particular case, since it seems that the `helm dependency update` command was skipped which led to your original error. With the directory structure mentioned above, how is your `devspace.yaml`'s `deployments` defined? Hopefully I can improve the PR to automatically add the flag for your case as well. If possible, it'd be great if you could try out that PR on your project too.

**Comment by tobalsgithub** [comment]
@lizardruss I was able to give your PR a try, and added some debugging to see what might be going on. 

It looks to me like right [here](https://github.com/devspace-sh/devspace/pull/2545/files#diff-d3fb0c0676b5a78307ff25676c948d7cc720dd6389177702a2f8ae413ecd1550L111), the `chartPath` is set incorrectly. I'm seeing something that looks like

```
/Users/<username>/<path>/<to>/<where>/<I>/<ran>/<devspace>/Users/<username>/<path>/<to>/<where>/<I>/<ran>/<devspace>/helm/<chart-directory>
```

You can see that `/Users` is in there twice. And I think what's going on is that the `chartName` variable is actually set to the path of the chart, not the name of the chart. So when you do `filepath.Join(ctx.WorkingDir(), chartName)` to get `chartPath`, it's not giving us what we want.

**Comment by tobalsgithub** [comment]
If I just take out the `filepath.Join(ctx.WorkingDir(), chartName)` piece completely and just use `chartName` instead, everything works as I expect it to. I think this all may come down to the fact that `chartName` is actually the path to the chart, not the name of the chart.

**Comment by tobalsgithub** [comment]
There's a separate question here around why we're putting the `--dependency-update` code behind an `if` check on whether the directory exists. Seems like if the `chartName` is not a valid path to a chart that we have bigger problems than whether we should run a dependency update 🤷 

But there may be a good reason for that that I'm not aware of.

**Comment by lizardruss** [comment]
Is the name of the chart a full path? I think the intent was for it to be a relative path from `devspace.yaml`

**Comment by tobalsgithub** [comment]
Our chart names are relative, not absolute. I think that particular variable is getting resolved to the full path way up [here](https://github.com/lizardruss/devspace/blob/6b1c7629946f560b7ef278d3c8e070947c092a0b/pkg/devspace/helm/v3/client.go#L68) inside that function. So when you're resolving it again down [here](https://github.com/lizardruss/devspace/blob/6b1c7629946f560b7ef278d3c8e070947c092a0b/pkg/devspace/helm/v3/client.go#L111) it ends up double resolved.

**Comment by lizardruss** [comment]
@tobalsgithub I see, my tests weren't hitting that since I was only using `name`, but I see it gets doubled when using `path`. I've update the PR and added some tests, so hopefully it works for you again.
