### ISSUE TITLE
Allow a way to ignore helm depdencies

### ISSUE THREAD

**Issue by ADustyOldMuffin** [devspace-sh/devspace#2533]
**Is your feature request related to a problem?**
Yes, we currently have a helm chart that we disable dependencies for via conditions because we don't use them, but since Devspace updates dependencies anyway it will download them. We've found that a server serving the dependencies is flaky and is causing our devspace setup to also be flaky.

**Which solution do you suggest?**
Allow a way for users to specify if dependencies should be updated on install/upgrade.

**Which alternative solutions exist?**
Don't update dependencies and instead just run an upgrade/install.

**Additional context**
The helm chart is Temporal.

**Comment by FabianKramm** [comment]
@ADustyOldMuffin thanks for creating this issue! We could add an option similar to
```
deployments:
  my-deployment:
    helm:
      ...
      disableDependencyUpdate: true
```
Would that solve your use case?

**Comment by ADustyOldMuffin** [comment]
Yes that'd be perfect!

**Comment by alexissellier** [comment]
I can work on this ticket if you want @FabianKramm

**Comment by FabianKramm** [comment]
@alexissellier yes that would great, thanks!
