### ISSUE TITLE
localRegistry option to select the buildkit image

### ISSUE THREAD

**Issue by d-bauer** [devspace-sh/devspace#2538]
For the local registry there is the option "Image of the local registry" You can define a local image. This image is only for the registry image. But the local registry needs another image, buildKit.

Is it possible to set another option for the buildkit Image, so you can pull a local image as well?

In my case, I can only pull docker images from a local repository (Artifactory). When I set the image to the local repository, it works fine. The container registry will be deployed in the cluster and the image is pulled. The first container starts. To get the registry finally working, another container starts and the image "moby/buildkit:master-rootless" is pulled, from docker hub and this is not working for me.

**Comment by FabianKramm** [comment]
@d-bauer thanks for creating this issue! Yes we can do that!
