### ISSUE TITLE
npm install fails with npm >9.0.0

### ISSUE THREAD

**Issue by kienhoefr** [devspace-sh/devspace#2541]
**What happened?**
When trying to install devspace with npm >9.0.0 the install fails with the following error:

```
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js install
npm ERR! Error: Command failed: npm bin -g
npm ERR!     at checkExecSyncError (node:child_process:885:11)
npm ERR!     at execSync (node:child_process:957:15)
npm ERR!     at continueProcess (C:\Users\USER\AppData\Roaming\npm\node_modules\devspace\index.js:227:35)
npm ERR!     at C:\Users\USER\AppData\Roaming\npm\node_modules\devspace\index.js:476:15
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     <Buffer 55 6e 6b 6e 6f 77 6e 20 63 6f 6d 6d 61 6e 64 3a 20 22 62 69 6e 22 0a 0a 54 6f 20 73 65 65 20 61 20 6c 69 73 74 20 6f 66 20 73 75 70 70 6f 72 74 65 64 ... 31 more bytes>,
npm ERR!     <Buffer >
npm ERR!   ],
npm ERR!   pid: 10316,
npm ERR!   stdout: <Buffer 55 6e 6b 6e 6f 77 6e 20 63 6f 6d 6d 61 6e 64 3a 20 22 62 69 6e 22 0a 0a 54 6f 20 73 65 65 20 61 20 6c 69 73 74 20 6f 66 20 73 75 70 70 6f 72 74 65 64 ... 31 more bytes>,
npm ERR!   stderr: <Buffer >
npm ERR! }
npm ERR! Error finding binary installation directory
```

[npm removed the ](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/)`npm bin` command in v9

**What did you expect to happen instead?**

devspace is installed successfully

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. Install npm v9 or above: `npm i -g npm@latest`
2. Try to install devspace `npm i -g devspace`

**Local Environment:**

* DevSpace Version: N/A
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: N/A
* Kubernetes Version: N/A

**Comment by lizardruss** [comment]
Hello! Thanks for reporting this. For now, a workaround would be to use one of the other installation methods until we catch up to this `npm` release 👍
