### ISSUE TITLE
build option force-rebuild is always true

### ISSUE THREAD

**Issue by alexissellier** [devspace-sh/devspace#2567]
**What happened?**

When building an image, the `--force-rebuild` flag is always true leading to image rebuilding even if the docker context did not change or even if `rebuildStrategy: ignoreContextChanges` is specify

**What did you expect to happen instead?**
I expect the flag to be set to ``` false ``` by default and its value controlled by \`\`--force-rebuild\`

**How can we reproduce the bug?** (as minimally and precisely as possible)

Build any image you want using the `build_image` pipeline function

**Anything else we need to know?**

**Comment by lizardruss** [comment]
Hello! I left an explanation in the PR, but as it stands the default is true as reflected in the [docs](https://www.devspace.sh/docs/cli/devspace_build#flags). It can be disabled by passing `devspace build --force-build=false`. For other commands, the default is `false`.
