### ISSUE TITLE
devspace dev selects wrong pod (every time)

### ISSUE THREAD

**Issue by withinboredom** [devspace-sh/devspace#2569]
**What happened?**
`devspace dev` is selecting the wrong pod, was working fine in <6.3.0. After today's update, it can't get it right.

**What did you expect to happen instead?**
The correct pod to be selected.

**How can we reproduce the bug?** (as minimally and precisely as possible)

2 images deployed, but only one selected via an image selector. The wrong image is selected. Label selector works fine.

My devspace.yaml:

```
version: ...
...
```

**Local Environment:**

* DevSpace Version: \[use `devspace --version`\]
* Operating System: windows | linux | mac
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
* Cloud Provider: google | aws | azure | other
* Kubernetes Version: \[use `kubectl version`\]

**Anything else we need to know?**

**Comment by lizardruss** [comment]
@withinboredom Thanks for raising this issue. It seems the `devspace.yaml` contents didn't get included.

**Comment by lizardruss** [comment]
@withinboredom I believe this issue may be related to a breaking change in the 6.3.0 release. Could you re-test with 6.3.1 and let us know if the issue persists?

**Comment by lizardruss** [comment]
@withinboredom Closing this issue for now. Please re-open if still an issue!
