### ISSUE TITLE
Add implicit patch during dev to unset readOnlyRootFilesystem

### ISSUE THREAD

**Issue by meyfa** [devspace-sh/devspace#2572]
**Is your feature request related to a problem?**

Our base Helm chart has `securityContext.readOnlyRootFilesystem` set to `true` on its container to improve production security. During development with `devspace dev`, this causes the following error message:

```
start_dev: start sync: error executing tar: tar: can't remove old file devspacehelper: Read-only file system
: command terminated with exit code 1
fatal exit status 1
```

**Which solution do you suggest?**

The docs describe a number of implicit patches applied by DevSpace to dev containers: [https://www.devspace.sh/docs/configuration/dev/modifications/patches#implicit-patches](https://www.devspace.sh/docs/configuration/dev/modifications/patches#implicit-patches)

I propose adding the following patch:

```
- op: remove
  path: spec.containers[].securityContext.readOnlyRootFilesystem
```

In my opinion, this makes sense since a read-only filesystem could never work with DevSpace, so this should be unset by default.

**Which alternative solutions exist?**

We are currently applying this patch manually, which works fine, but clutters devspace.yaml. For reference, this is part of our devspace.yaml:

```
dev:
  app:
    patches:
      - op: remove
        path: spec.containers.name=${DEVSPACE_NAME}.securityContext.readOnlyRootFilesystem
```

**Additional context**

I'm using DevSpace version 6.3.0.

**Comment by FabianKramm** [comment]
Hey @meyfa ! Thanks for opening up this issue! Yes I agree, that makes sense, we will add this as an implicit patch.
