### ISSUE TITLE
Can any GUI or api interface interact?

### ISSUE THREAD

**Issue by mmm8955405** [devspace-sh/devspace#2583]
Can any GUI or api interface interact?
Docker deployment is not supported at present. I don't want to deploy to k8s。
There are still many problems.

There are still many problems. Error reported by node yarn on Windows！

**Comment by 89luca89** [comment]
Hi @mmm8955405 
from what I understand, you want to use devspace without k8s?
As stated specifically in the documentation first page Devspace is a [Client-Only Developer Tool for Cloud-Native Development with Kubernetes
](https://github.com/devspace-sh/devspace#client-only-developer-tool-for-cloud-native-development-with-kubernetes) so it is designed specifically to work with k8s
