### ISSUE TITLE
Add cli command to display helm chart with values from devspace.yaml and values.yaml

### ISSUE THREAD

**Issue by marcm-ml** [devspace-sh/devspace#2605]
**Is your feature request related to a problem?**
No, just nice to have

**Which solution do you suggest?**
Use this command under the hood with the correct values patched from devspace.yaml for debugging:

```
helm template . -f values.yaml
```

**Which alternative solutions exist?**
Basically provide them manually via `--set` in the helm command, e.g:

```
helm template . -f values.yaml --set key=value --set key2=value2
```

**Comment by lizardruss** [comment]
@marcm-ml Hello! There is `devspace deploy —render` that will print the rendered helm charts without deploying. Will that meet your needs?

**Comment by marcm-ml** [comment]
When i try this command it doesn't print anything but the deploy messages. The application is also fully deployed after that although the command suggest something else.

**Comment by lizardruss** [comment]
Could you share your `devspace.yaml` and the DevSpace version you're using. This seems like there could be a bug with the `devspace deploy --render`.

**Comment by marcm-ml** [comment]
I am afraid I cannot share this publicly due to compliance reasons and right now I don't have the time to create a reproducible script
