### ISSUE TITLE
DevSpace does not work with Agones properly.

### ISSUE THREAD

**Issue by portlek** [devspace-sh/devspace#2611]
**What happened?**
I cannot use DevSpace with Agones's GameServers.
I assume devspace works one of these; deployment, statefulset or replica set. and since Agones does not use any of them, it cannot replace the pod with the new one.
It's creating the pod normally but i cannot use devspace dev command to update the pod or develop my project.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Create a Fleet with Agones then use that Fleet in DevSpace with helm chart.

**Local Environment:**

* DevSpace Version:  6.3.1
* Operating System: windows
* ARCH of the OS: AMD64

**Kubernetes Cluster:**

* Cloud Provider: Rancher Desktop
* Kubernetes Version: 1.25.7

**Anything else we need to know?**
The 'devspace dev' logs:

```
info Using namespace 'minecraft'
info Using kube context 'rancher-desktop'
Ensuring image pull secret for registry: hub.docker.com...
Couldn't retrieve username for registry  from docker store
Couldn't retrieve password for registry  from docker store
local-registry: Starting Local Image Registry
build:proxy Skip building image 'proxy'
deploy:proxy Skipping deployment proxy
start_dev: replace pod: couldn't find a matching deployment, statefulset or replica set
fatal exit status 1
```

Deployments (namespace:name):
agones:agones-allocator
agones:agones-controller
agones:agones-ping
kube-system:coredns
kube-system:local-path-provisioner
kube-system:metrics-server
kube-system:traefik
minecraft:registry

Replicasets:
agones:agones-allocator-69d6c4c8d7
agones:agones-controller-84b8c46f87
agones:agones-ping-6bcdc64f94
kube-system:coredns-597584b69b
kube-system:local-path-provisioner-79f67d76f8
kube-system:metrics-server-5f9f776df5
kube-system:traefik-66c46d954f
minecraft:registry-6ff74dbf

Statefulsets:
\-empty-

Pods:
kube-system:helm-install-traefik-crd-kbwxr
kube-system:helm-install-traefik-ctqng
kube-system:svclb-agones-ping-http-service-d7427603-86ml8
kube-system:svclb-agones-allocator-5f2bf405-v7cvb
kube-system:svclb-traefik-e2aa7389-4rdj2
kube-system:svclb-agones-ping-udp-service-69cedc5b-84xg6
kube-system:local-path-provisioner-79f67d76f8-gb7mz
agones:agones-ping-6bcdc64f94-rvjk4
agones:agones-controller-84b8c46f87-xlcjm
agones:agones-allocator-69d6c4c8d7-6jxdw
agones:agones-allocator-69d6c4c8d7-wpsx5
kube-system:coredns-597584b69b-qv9pv
kube-system:traefik-66c46d954f-kffnc
agones:agones-ping-6bcdc64f94-m7sdk
agones:agones-allocator-69d6c4c8d7-q6579
kube-system:metrics-server-5f9f776df5-bmjr8
minecraft:registry-6ff74dbf4d-9jwbz
minecraft:proxy-fleet-pwtvm-4jb7j

**Comment by FabianKramm** [comment]
@portlek thanks for creating this issue! What are trying to do there, and what instead of a deployment / replicaset is your configuration using?

**Comment by FabianKramm** [comment]
@portlek ah thanks for the additional information, mhh interesting. In general the problem here is that DevSpace cannot know of every CRD that creates pods directy, so its hard to support all these, and directly replacing the pod wouldn't work I guess since the CRD would recreate the pod. For now I guess the best bet would be to try to create the development pod through a deployment / statefulset / replicaset until we have a better solution
