### ISSUE TITLE
Stdout not showing in light background terminal.

### ISSUE THREAD

**Issue by murarisumit** [devspace-sh/devspace#2651]
**What happened?**
When running devspace, output within "inverted commas" isn't visible.

Not sure but [https://github.com/devspace-sh/devspace/blob/main/pkg/devspace/dev/dev.go#L36](https://github.com/devspace-sh/devspace/blob/main/pkg/devspace/dev/dev.go#L36) explicitly mentioned white color is causing the issue
`			ctx.Log().Infof("DevSpace UI available at: %s", ansi.Color("http://"+serv.Server.Addr, "white+b"))`

```
dev:app Selected pod voyager-devspace-test-vc-devspace-657b784b97-sgtjt
dev:app open  Opening 'http://localhost:8089/' as soon as application will be started
dev:app ports Port forwarding started on: 3000 -> 3000, 9229 -> 9229
dev:app sync  Sync started on: ./server/dist <-> /home/ubuntu/deployment/voyager/dist
dev:app sync  Waiting for initial sync to complete
dev:app sync  Initial sync completed
dev:app ssh   Port forwarding started on: 10548 -> 8022
dev:app ssh   Use 'ssh app.devspace.devspace' to connect via SSH
```

It looks something like this in white background.

<img width="990" alt="image" src="[https://github.com/devspace-sh/devspace/assets/2667258/cfacedc2-a45a-4110-ab0d-bc7497a5a16a](https://github.com/devspace-sh/devspace/assets/2667258/cfacedc2-a45a-4110-ab0d-bc7497a5a16a)">

Looks completely fine with dark background
<img width="962" alt="image" src="[https://github.com/devspace-sh/devspace/assets/2667258/a9edbfbb-1dd6-4b84-9714-6a2233c90740](https://github.com/devspace-sh/devspace/assets/2667258/a9edbfbb-1dd6-4b84-9714-6a2233c90740)">

**What did you expect to happen instead?**
Wanted stdout to be visible.

**How can we reproduce the bug?** (as minimally and precisely as possible)
run commands in light background terminal

**Comment by batizhevsky** [comment]
Sorry, but I don't think this solves the problem, because sometimes this tool is used internally by another script.  I've also seen that the code supports the `NO_COLOR` env variable, but instead of using a specific colour or cleaning, wouldn't it be better to just make text bold when you want to highlight something? You project is used by many people, and I think everyone would appropriate some accessibility.    

Thank you for supporting this project
