### ISSUE TITLE
Devspace project name in devspace.yaml has to be unique

### ISSUE THREAD

**Issue by EdwinPhilip** [devspace-sh/devspace#2654]
**What happened?**
We just tried to upgrade to devspace 6.x from 5.x
We have a monolith repo with multiple k8s deployment from one helm chart. With 5.x, devspace.yaml name is not required. We use to run devspace dev targetting different deployments using label selector. With 6.x, the name in devspace.yaml is required field. But with value set for name, we can't run multiple devspace dev in one namespace targetting different deployments.

When we try to run, we are getting there is already session using devspace in this namespace

Any suggestions on how to proceed with this use case ?

**Comment by lizardruss** [comment]
Hi @EdwinPhilip!

Is this an error, or a message being logged? I see where we log `Skipping dependency X as it is currently in use by another DevSpace instance in the same namespace`, but that is expected since it's already been deployed.

Is this multiple users running DevSpace against the same namespace, or the same user?

It would be helpful if you could share the log output from running DevSpace with the `--debug` flag on.

Thanks!

**Comment by EdwinPhilip** [comment]
https://github.com/devspace-sh/devspace/blob/825e4d2c4c7dfd6e10acaf2767011e4f0dbf76c3/pkg/devspace/pipeline/pipeline.go#L108


This is the error i get.

**Comment by lizardruss** [comment]
If all your deployments are in the same `devspace.yaml` then I think your best option is to remove any `dev.*.terminal` configuration from your `devspace.yaml` and use `devspace enter -l app=app1` for a terminal to each deployment.

If your deployments are in dependencies, then the default pipeline for each dependency defaults to `deploy`. You should be able to `devspace dev` to each dependency as needed without issue. Another approach is to change the pipeline to `dev` for each dependency, and have one process handle the file syncing and port-forwarding for all deployments. In this case you would also need to use `devspace enter` for a terminal as above.

The major change with DevSpace 6 is it tries to run things concurrently to improve performance. As such, we needed a way to deduplicate the concurrency in the case of a dependency tree.

Let me know if neither of these scenarios applies to your situation, and provide an example devspace.yaml so I can reproduce the issue.

**Comment by EdwinPhilip** [comment]
My usecase is little different. We don't deploy with devspace instead we use devspace to replace existing pod and develop in it. So no dependencies or deploy pipelines, just only dev

I went with profiles to solve this issue
```
profiles: |-
  $(
  namedProfile="
  - name: namedProfile
    patches:
    - op: replace
      path: name
      value: ${label}
  "
  echo "$namedProfile"
  )
```
and `${label}` replaces with pod/deployment labels. With this, i was able to run multiple devspace dev in my monolith repo.

We can close this ticket
