### ISSUE TITLE
permission denied when using run_watch with directory glob patterns

### ISSUE THREAD

**Issue by lizardruss** [devspace-sh/devspace#2656]
**What happened?**
When using `run_watch` via custom command to restart `devspace dev` on local file changes, it seems using glob patterns with directories containing multiple files results in a `permission denied` error and no other output.

```
❯ devspace run watch
permission denied
```

**What did you expect to happen instead?**
Expected `devspace dev` to run and restart the container on changes.

**How can we reproduce the bug?** (as minimally and precisely as possible)

An example repository is provided [here](https://github.com/lizardruss/devspace-debug/tree/run_watch_with_globs). Running `devspace dev` will show the error, while running `devspace --config=devspace.works.yaml dev` will work. The main difference is that the files are enumerated vs matching with a glob pattern.

**Local Environment:**

* DevSpace Version: v6.3.2
* Operating System: mac
* ARCH of the OS: ARM64

**Comment by 89luca89** [comment]
I've pinned down the issue to a "shell" issue

If we run `-p ./cmd/**/*.go` this will be evaluated by the shell
If we run `-p "./cmd/**/*.go"`  with quotes, it works

This will result in a different thing, as we end up with 2 arguments for a single flag, that is equivalent to running

`-p /path/to/a /path/to/b -p /path/to/c /path/to/d` that will only take the a and c paths, and yield the same permission denied error
