### ISSUE TITLE
devspace dev --show-ui false expected to not start Devspace UI

### ISSUE THREAD

**Issue by EdwinPhilip** [devspace-sh/devspace#2657]
**What happened?**
We have another microservice that uses the Devspace UI default port 8090. I had to stop `devspace dev` and run yarn start in the other service. Then start `devspace dev` so that it takes different port

Currently i don't see a way to stop running devspace ui or change port number when started by devspace dev

**What did you expect to happen instead?**
I would like disable starting devspace ui by default

Possible solution:
`devspace dev --show-ui false`  to not start devspace ui

**Comment by lizardruss** [comment]
Can you try:
```shell
> devspace dev --show-ui=false
```

It doesn't look like `--show-ui false` works. According to [this comment](https://github.com/spf13/cobra/issues/613#issuecomment-357706597), I think it gets interpreted as `--show-ui` (true).

If you'd like to be able to specify a ui port instead that might require a code change. It looks like it was possible once upon a time.

**Comment by EdwinPhilip** [comment]
By default, without `--show-ui` , `devspace dev` starts ui server and serves at localhost:8090
Not sure why we then have another flag here if the ui server starts by default.

I would like to contribute if this needs code change. 
i see that code reference here
https://github.com/devspace-sh/devspace/blob/825e4d2c4c7dfd6e10acaf2767011e4f0dbf76c3/cmd/run_pipeline.go#L90


Either would like to make `--show-ui=false` work or provide a way change port number

can you help me if i am looking at the right place ?

**Comment by lizardruss** [comment]
```shell
devspace dev --show-ui=false
```

^ This already works for me to disabling the UI. If you'd like to submit a PR to add a `--ui-port` flag, that would be great. I believe the changes would be in the same file, and just a matter of adding the flag.

**Comment by EdwinPhilip** [comment]
I just tried 
```
devspace dev --show-ui=false
```
Didn't work for me. i can still access devspace ui at localhost:8090

DevSpace version : 6.3.2

**Comment by lizardruss** [comment]
Ah strange. I think this will need a deeper look. The flag seems to only affect whether a message is logged, and not whether the server is started or not. I don't have enough context to know the reasoning behind that. Adding the `--ui-port` flag may be the easier option since it seems this server is involved in dependency tracking too.
