### ISSUE TITLE
Automatically installing debug dependencies

### ISSUE THREAD

**Issue by jackwilsdon** [devspace-sh/devspace#2679]
**Is your feature request related to a problem?**
When using devspace, I have to maintain 2 dockerfiles - one for production and one for development. The production image only contains the compiled binary, whilst the development image also contains debugging tooling (e.g. `dlv` for Go).

**Which solution do you suggest?**
Support automatic installation of debug dependencies in a container. [Skaffold](https://skaffold.dev/) implements this by using an init container which populates a shared volume (there's a bit more information in the [documentation](https://skaffold.dev/docs/workflows/debug/#configuring-container-images-for-debugging)).

**Which alternative solutions exist?**

* Maintaining two separate dockerfiles
* Using one of the [dev-optimized images](https://www.devspace.sh/docs/configuration/dev/modifications/dev-image#dev-devImage) (this only works if you don't need additional customizations on top of the image)
* Using [file synchronization](https://www.devspace.sh/docs/configuration/dev/connections/file-sync) to synchronize development dependencies into the container (this requires including the dependencies in-tree)

**Additional context**

**Comment by lizardruss** [comment]
@jackwilsdon To avoid maintaining two Dockerfiles, I've used multi-stage builds in the past. It would still result in two distinct images, but [devImage](https://www.devspace.sh/docs/configuration/dev/modifications/dev-image) makes switching pretty painless.

**Comment by jackwilsdon** [comment]
Ah that's not half bad, I see devspace does have support for setting `target`, so I could have something like:

```
FROM golang:1.20.5-alpine3.18 AS builder
# Install dlv and build app.

FROM scratch AS development
COPY --from=builder /dlv /
COPY --from=builder /myapp /
ENTRYPOINT ["/dlv", "/myapp"]

FROM scratch AS production
COPY --from=builder /myapp /
ENTRYPOINT ["/myapp"]
```

And have two images in my `devspace.yaml` with different `target` values.

**Comment by lizardruss** [comment]
Closing for now. Feel free to reopen if there are advantages to the Skaffold approach that we're not considering.

I think we preferred this approach since the devImage can be built once and shared across a team. It looks like [devImage](https://www.devspace.sh/docs/configuration/dev/modifications/dev-image) also covers the replica count and probe modifications needed as well.
