### ISSUE TITLE
Support GUI

### ISSUE THREAD

**Issue by raojinlin** [devspace-sh/devspace#2685]
**Is your feature request related to a problem?**
It's not very convenient to open a terminal every time for development.
If I have four microservices projects to coordinate development, then I need to open four terminals.

**Which solution do you suggest?**
Integrating devspace.yaml configuration and workspace selection into DevSpace GUI

1. . Users can start and destroy development environments from the file system.

**Which alternative solutions exist?**

**Additional context**

**Comment by FabianKramm** [comment]
@raojinlin thanks for creating this issue! We have a devspace UI, have you taken a look at this?

**Comment by raojinlin** [comment]
@FabianKramm Understood. Are there any plans for future support?
