### ISSUE TITLE
Document default hook timeout

### ISSUE THREAD

**Issue by tobalsgithub** [devspace-sh/devspace#2701]
**What happened?**  
The documentation for hooks makes it sound like the default timeout is no timeout at all. The language sounds like the hook will wait indefinitely for the pod to be ready. But in reality, there is a [150 second hook timeout](https://github.com/devspace-sh/devspace/blob/45f987c9f6d9de83c22310e3204486882f980479/pkg/devspace/hook/remote_hook.go#L81C23-L81C23). 

**What did you expect to happen instead?**  
It'd be great if the default hook timeout was documented. Our team spent some time digging through the code before we finally found the default timeout of 150 seconds. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Just checkout the documentation [here](https://github.com/devspace-sh/devspace/blob/45f987c9f6d9de83c22310e3204486882f980479/pkg/devspace/hook/remote_hook.go#L81C23-L81C23).

**Comment by lizardruss** [comment]
This will be updated by [this PR](https://github.com/devspace-sh/devspace/pull/2714), which will add in the generated config reference for hooks and show the default value.
