### ISSUE TITLE
autoscaling/v2beta1 is deprecated on k8s 1.25. autoscaling/v2 is required

### ISSUE THREAD

**Issue by pablorsk** [devspace-sh/devspace#2703]
**What happened?**  

K8S 1.24 reachs end of life. K8s 1.25, released on 2023-08-23, is mandatory on DO. But, autoscaling v2 is the valid value today for autoscaling. v2beta1 is autoscaling/v2beta1 is no longer supported.

When I try to deploy, I get:

`Error: UPGRADE FAILED: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"`

**What did you expect to happen instead?**  

- autoscaling/v2 on version.

**How can we reproduce the bug?**

On any component chat deployment: 

```
   values:
      autoScaling:
        horizontal:
          maxReplicas: 16
          averageCPU: 180m
```

My devspace.yaml:
```
version: v2beta1
...
```

**Local Environment:**  
- DevSpace Version: devspace version 6.3.2
- Operating System: mac pro 
**Kubernetes Cluster:**  
- Cloud Provider: do
- Kubernetes Version: "v1.27.2"

**Anything else we need to know?**  

 More information on [stackoverflow](https://stackoverflow.com/questions/76483758/helm-upgrade-fail-after-upgrade-to-kubernetes-1-25-due-to-change-in-horizontalpo) and [issue 97](https://github.com/loft-sh/component-chart/issues/97).

**Comment by lizardruss** [comment]
[PR submitted here](https://github.com/loft-sh/component-chart/pull/103)

**Comment by pablorsk** [comment]
Thanks!

What is the next step? wait to devspace release or is there a way to use the new component chart?

**Comment by lizardruss** [comment]
@pablorsk the component chart was just released, so you can update the chart version to use it now. DevSpace will also be released with the new component chart version as the default.
