### ISSUE TITLE
[Feature Request] Ability to use multiple .env files to load data from

### ISSUE THREAD

**Issue by karbowiak** [devspace-sh/devspace#2713]
Hi there.

I am trying to figure out a way to read environment variable data from multiple sources.

In my use case i have a `devspace.env` in each project, pre-defining certain values specific to that project.
But at the same time, the project could have it's own `.env` with certain values inside of it, that should NOT be added to git.
And each developer also have their own `user.env` located in their home directory, that can be used to pre-fill certain vars in Devspace.

However, i cannot for the life of me find a way to do this, beyond having them pre-cat all the files together, and then telling Devspace using `DEVSPACE_ENV_FILE` to use that one in particular.

Would it be a huge thing to make `DEVSPACE_ENV_FILE` have the ability to load from multiple in sequence?

It could look like:

current functionality
```yaml
vars:
  DEVSPACE_ENV_FILE: "devspace.env"
```

proposed:
```yaml
vars:
  DEVSPACE_ENV_FILES:
    - devspace.env
    - .env
    - ~/.users.env
```

With both being a valid use case (Mutually exclusive tho, can't use both at the same time)

**Comment by lizardruss** [comment]
@karbowiak Hello! Thanks for submitting this feature request. At some point, we decided not to support multiple .env files, and `DEVSPACE_ENV_FILE` was only to support earlier schemas (v1beta11 and before) where things were implicitly loaded.

I think the encouraged approach now is to define an entry in `vars` for each variable. DevSpace will prompt for each variable and cache the responses in `.devspace/cache.yaml` for the vars that don't have previously cached values. This acts similar to a user specific set of environment variables.

FWIW, you can still [specify that the variable value should come from an environment variable](https://www.devspace.sh/docs/configuration/variables#from-env-vars), but managing those environment variables happens independently of DevSpace, usually though `.bashrc` files or similar.

Please take a look and see if converting to [vars](https://www.devspace.sh/docs/configuration/variables) would meet your needs, and if not we'll discuss expanding support for `.env` files.

**Comment by karbowiak** [comment]
Hi @lizardruss 

My thought was actually to use an import with enable/disable depending on if an ENV var was set.

```
imports:
  - path: ./extravars/var1.yaml
    enabled: $( if [ "${SOME_VAR}" != "" ]; then echo "true"; else echo "false"; fi )
```
And then have it use the environment to fill out those parameters.

As for `.bashrc`, the problem with getting the developers to add loading multiple sources of env vars from their own environment is.. the developers 😂 trying to corral them into doing the same thing, from their myriad of OS installations. Might as well try and herd cats 😅 

So my hope was to contain it entirely in Devspace.

But i understand the reluctance, i can totally see it becoming a mess - like if two ENV vars contains the same, is it just overwrite the previous? should the user be told? eek 😬

**Comment by lizardruss** [comment]
@karbowiak This might be another way to achieve what you'd like to do:
```yaml
version: v2beta1

imports:
  - path: ./extravars/var1.yaml
    enabled: $(source local.env && if [ "${SOME_VAR}" != "" ]; then echo "true"; else echo "false"; fi)
```
