### ISSUE TITLE
Debug Flag does not print debug logs

### ISSUE THREAD

**Issue by mschoenlaub** [devspace-sh/devspace#2717]
**What happened?**  
`devspace deploy --debug` does not change the log level and I still only see `info` or higher messages.

**What did you expect to happen instead?**  
`devspace deploy --debug` shows actual `debug` level log entries.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
Just use the project in `examples/quickstart`.

**Local Environment:**  
- DevSpace Version:  6.3.3
- Operating System: mac
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: Client Version: v1.24.2, Kustomize Version: v4.5.4, Server Version: v1.25.12-eks-2d98532

**Anything else we need to know?**  

It also doesn't seem that an actual stacktrace is printed out on an error, is it limited to specific errors?

**Comment by lizardruss** [comment]
Hello! Thanks for reporting this issue. I can't seem to reproduce it with 6.3.3 or on the `main` branch. Here's a copy of the output I got, perhaps you could provide your log output as well?

```shell
> cd examples/quickstart
> devspace deploy --debug
16:49:10 info Using namespace 'loft'
16:49:10 info Using kube context 'kind-kind'
16:49:10 debug Use config:
version: v2beta1
name: quickstart
deployments:
    quickstart:
        name: quickstart
        helm:
            values:
                containers:
                    - image: loftsh/javascript:latest
dev:
    my-dev:
        name: my-dev
        imageSelector: loftsh/javascript:latest
        sync:
            - path: ./
              excludeFile: .gitignore
        terminal:
            command: ./devspace_start.sh
        ssh: {}
        ports:
            - port: "3000"
        open:
            - url: http://localhost:3000


16:49:10 debug Run pipeline:
name: deploy
run: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all


16:49:10 run_dependencies --all
16:49:10 Marked project excluded: quickstart
16:49:10 ensure_pull_secrets --all
16:49:10 build_images --all
16:49:10 create_deployments --all
16:49:10 Deploying 1 deployments concurrently...
16:49:10 deploy:quickstart Skipping deployment quickstart
16:49:10 Deploying 0 deployments concurrently
16:49:10 debug Wait for dev to finish
```
