### ISSUE TITLE
Running Build_images & Create_Deployments  - deployment gets duplicate tags

### ISSUE THREAD

**Issue by danielehq** [devspace-sh/devspace#2724]
**What happened?**  
My pipeline with these functions:
build_images build-svc --set image=organazation/test  -t loft-${LOFT_USERNAME}-${USER}.${DEVSPACE_TIMESTAMP}
image is build successfully with repository and tag.
create_deployments deployment1 --set helm.values.test.image.tag=loft-${LOFT_USERNAME}-${USER}.${DEVSPACE_TIMESTAMP} --set helm.values.test.image.repository=organazation/test

**What did you expect to happen instead?**  
Deployment to be deployed with one tag > loft-${LOFT_USERNAME}-${USER}.${DEVSPACE_TIMESTAMP}
The pod is stuck in InvalidImageName
When i describe the pod i see this:

  Warning  Failed         10m (x12 over 11m)   kubelet            Error: InvalidImageName
  Warning  InspectFailed  104s (x50 over 11m)  kubelet            Failed to apply default image tag "docker.io/organazation/test:loft-admin-danieleh.1696164503:loft-admin-danieleh.1696164503": couldn't parse image reference "docker.io/organazation/test:loft-admin-danieleh.1696164503:loft-admin-danieleh.1696164503": invalid reference format

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My images part in devspace:
images:
  build-svc:
    image: organazation/test
    tags:
      - loft-${LOFT_USERNAME}-${USER}.${DEVSPACE_TIMESTAMP}
    context: ${SVC_DOCKER_FILE}
    dockerfile: ${SVC_DOCKER_FILE}/Dockerfile
    docker:
      disableFallback: true

devspace cli 6.3.3
k8s 1.26.7

My devspace.yaml:
```
version: v2beta1
...
```

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**

**Comment by lizardruss** [comment]
@danielehq 

Hello! DevSpace is replacing `organazation/test` with the image + tag. This is to support charts that only have single value for the image, but DevSpace still needs to inject the auto-generated tag. This can be turned off by setting [updateImageTags](https://www.devspace.sh/docs/configuration/deployments/#deployments-updateImageTags) to false.

Since you're modify the config through `create_deployments` setting that flag would look like:
```shell
    create_deployments deployment1 \
      --set updateImageTags=false \
```

**Comment by lizardruss** [comment]
Closing as I believe this is resolved 👍

**Comment by danielehq** [comment]
Yea,
Thank you very much for all the help and the support!
