### ISSUE TITLE
Documentation conflict for automatic creation of pull secrets

### ISSUE THREAD

**Issue by LISTERINE** [devspace-sh/devspace#2730]
**What happened?**  
Using the information detailed in https://www.devspace.sh/docs/configuration/images/pull (6.x, latest) that say to use the field `createPullSecrets` to disable automatic creation of pull secrets, pull secrets are still created.
The 5.x docs https://www.devspace.sh/docs/5.x/configuration/images/pull-secrets say to use the field `createPullSecret`, which *does* disable automatic creation of pull secrets.

**What did you expect to happen instead?**  
Documentation that indicates `createPullSecrets` should be updated to the working `createPullSecret`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Setting the plural setting `createPullSecrets` to `false` when running a build will still create pull secrets. Using the singular version will prevent creation.

My devspace.yaml:
```
version: ...
...
```

**Local Environment:**  
- DevSpace Version: 6.3.2
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: v1.25.11-gke.1700

**Anything else we need to know?**  

This can easily lead to leaked credentials of a user that believes they've taken measures to prevent their creds from being uploaded to a remote server.

**Comment by lizardruss** [comment]
@LISTERINE Hello! Thanks for reporting this. We'll get the documentation updated.

FWIW, the schema validation should fail and prevent the secrets from being leaked. At least that's what I observed when trying it with this `devspace.yaml`:
```yaml
version: v2beta1

images:
  default:
    image: myregistry.foo.bar/myusername/devspace
    createPullSecrets: false
```

Output:
```shell
info Using namespace 'pull-secrets'
info Using kube context 'kind-kind'
fatal error loading config: yaml: unmarshal errors:
  Parsed Config:
    1: images:
    2:     default:
    3:         createPullSecrets: false
    4:         image: myregistry.foo.bar/myusername/devspace
    5: name: pull-secrets
    6: version: v2beta1
  Errors:
    line 3: field createPullSecrets not found in type latest.Image (line 3: createPullSecrets: false)
```

If you have an example `devspace.yaml` where this didn't occur please share and we'll take a look!

**Comment by LISTERINE** [comment]
Thanks for the update!
