### ISSUE TITLE
Supports non k8s environments

### ISSUE THREAD

**Issue by mmm8955405** [devspace-sh/devspace#2734]
Supports non k8s environments
For example:  Docker Podman

**Comment by FabianKramm** [comment]
@mmm8955405 thanks a lot for creating this issue! Its not a priority for us right now, but good idea!

**Comment by madhavajay** [comment]
@mmm8955405 I can highly recommend `k3d` which will run on both Docker and Podman.

**Comment by madhavajay** [comment]
> > @mmm8955405 I can highly recommend `k3d` which will run on both Docker and Podman.
> 
> This is a bad idea, and those who use Docker and Podman may not like k8s. And I have tried using k3s on Docker. But strange errors make it difficult for people to find a solution

Why is this a bad idea? Kubernetes is more than just containers. You can re-implement all that yourself but you end up swimming against the tide. The solution here is to miniaturize the kubernetes standard enough that it can be run in a single VM style scenario. That is what `kind` and `k3d` / `k3s` and other projects are doing.

**Comment by lizardruss** [comment]
FWIW, there is [devpod.sh](https://devpod.sh/) now. Closing since DevSpace will remain Kubernetes specific.
