### ISSUE TITLE
Replaced docker container uses amost 1gb memory.

### ISSUE THREAD

**Issue by jaketakula** [devspace-sh/devspace#2758]
first of all, Thx for creating `devspace` which really speeds up dev loop.

I am using dev image typescript:18-alpine
but i found the docker container use amost 1gb memory which increases the costs in cloud: aks

I used 512Mi and 500m resoiuces. but it failed at `pnpm i` due to the oom.
so is there a way to use less memory and cpu resources when doing `devspace dev` ?

**Comment by lizardruss** [comment]
@jaketakula Thanks for reporting this issue. Were you able to find a solution to this? `pnpm` seems like it might be using a lot of memory, and I don't see where it's installed in the image:
```sh
❯ docker run -i -t --rm ghcr.io/loft-sh/devspace-containers/typescript:18-alpine sh -c pnpm
sh: pnpm: not found
```

IIRC, there's a way to limit the amount of memory that NodeJS can use, which may allow `pnpm` to run within the memory limits you've given. This is specific to NodeJS, and not something `devspace` can configure. Here's a [SO answer](https://stackoverflow.com/questions/7193959/memory-limit-in-node-js-and-chrome-v8) that might be helpful.
