### ISSUE TITLE
Is the `--config` flag deprecated for `devspace sync` starting v6.0?

### ISSUE THREAD

**Issue by MaxSchambach** [devspace-sh/devspace#2792]
I've noticed that all documentation of the `--config` flag in `devspace sync` have disappeared, from both the CLI manual as well as the user documentation starting version 6.0. However, the flag still works and I do not see anything related in the release notes / breaking changes notes.

Either way, I'm left wondering, whether this implies that the `--config` flat is now deprecated and should not be used anymore?

In fact, no deprecation warning is shown, and not using the flag actually prints a hint [1] about using it, so I am a bit confused...

[1] "warn If you want to use the sync paths from `devspace.yaml`, use the `--config=devspace.yaml` flag for this command."

**Comment by lizardruss** [comment]
@MaxSchambach Hello! Yes, this flag has been deprecated, however we don't have any pending plans to remove it either. As [this (hidden) description](https://github.com/devspace-sh/devspace/blob/b21c769305d619de6eca42ec58e08c2e757cdc78/cmd/flags/flags.go#L64) implies, you may use the `DEVSPACE_CONFIG` environment variable instead.

FWIW, I still use this flag frequently when testing things out.

**Comment by MaxSchambach** [comment]
Thank you for the quick response! Alright, I'll keep using it then. Not passing ``--config`` for me also yields the warning I mentioned above, which I belive originates [here](https://github.com/devspace-sh/devspace/blob/b21c769305d619de6eca42ec58e08c2e757cdc78/cmd/sync.go#L155). I think that's what confused me in the first place. If the flag is deprecated, that warning should point to the env variable instead, in my opinion :)
