### ISSUE TITLE
Is it possible to specify concurrency level for files sync?

### ISSUE THREAD

**Issue by petr-buchyn** [devspace-sh/devspace#2796]
I'm trying to use Devspace to sync files from a local machine to a big platform, deployed on Amazon EKS. There I have about 150 deployments I sometimes want to sync files to. I don't need continuous sync - just initial sync, after which I expect sync process to terminate (I use "noWatch" setting in my "devspace.yaml" for that). However, from what I see from the "devspace dev" command output - it syncs concurrently only to 2-3 pods, which is why my process of syncing files is really slow. 

I have 300mbps Internet, so issue is not my Internet speed. 

I would appreciate if there was a setting, that allows to specify concurrency level for files sync, e.g. how many pods does Devspace sync files to at any given moment. Is it possible to add such option? 

Thanks in advance.

**Comment by petr-buchin** [comment]
Is this project still supported?

**Comment by lizardruss** [comment]
@petr-buchin

Apologies for the delayed response. This isn't something that's currently supported. There isn't a concurrency setting, but you should be able to limit the number of syncs started at once with pipelines. Check out the Deploy / Sync / Open tab [here](https://www.devspace.sh/docs/configuration/pipelines/?x0=4).

I can help with an example configuration if needed. You might also join our slack community and as if other users have a solution they prefer.

**Comment by lizardruss** [comment]
@petr-buchin
Oh, I misunderstood that you wanted to _increase_ it and not limit it. Glad that you were able to find a solution! I would say that your case is non-typical usage, but if you would like to share an example for future users with this case, I think that could be very helpful.

Are you starting the additional `devspace sync` processes in a command or pipeline?
