### ISSUE TITLE
Remove DCO requirement from Pull Request workflow requirements

### ISSUE THREAD

**Issue by Andrioden** [devspace-sh/devspace#2797]
**Description**

Take a look at the commit history of https://github.com/devspace-sh/devspace/pull/2766/, i messed up my fork's main branch trying to adher to DCO check. Looking into why its needed, it looks overly bureaucratic.

Yes i feel slightly annoyed and stupid now, since i ran git commands i didnt fully understand, but still, i did it for seemingly unimportant reasons. : p

**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
- A) Add a disclaimer to https://github.com/devspace-sh/devspace/blob/main/CONTRIBUTING.md with whatever legalese reasons you have for requiring developers signoff.
- B) Remove it altogether

**Comment by lizardruss** [comment]
@Andrioden

DCO was added because DevSpace is a [CNCF Sandbox project](https://github.com/devspace-sh/devspace?tab=readme-ov-file#license). Here's a link to [their legalese regarding DCO](https://github.com/cncf/foundation/blob/main/dco-guidelines.md) :-)
