### ISSUE TITLE
devspace build --push

### ISSUE THREAD

**Issue by madhavajay** [devspace-sh/devspace#2858]
**Is your feature request related to a problem?**  
Yes, I want to build and push images without deploying to a cluster.

**Which solution do you suggest?**  
`devspace build --push` or something similar

**Which alternative solutions exist?**  
None that I know of, images seem to only be pushed on deploy.

**Additional context**  
Also it seems like the caching fails if the deployment fails which means rebuilding every time I tweak until the deployment works.

**Comment by ddziech** [comment]
How about just `devspace build`?
> devspace build
Builds all defined images and pushes them
