### ISSUE TITLE
devspace open will wait for a init container which is a sidecar

### ISSUE THREAD

**Issue by nberlee** [devspace-sh/devspace#2865]
**What happened?**  
In kubernetes 1.29 the Sidecar feature became general available. This means you have a init container which has a `restartPolicy: Always` runs forever, effectively as a sidecar. This is what istio uses to prevent a lot of [issues](https://istio.io/latest/blog/2023/native-sidecars/#sidecar-woes)

The problem is devspace open will wait for the init container to exit, therefore, devspace dev will never continue.

**What did you expect to happen instead?**  
If `restartPolicy` is defined in the init container it should just continue.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Use Kubernetes 1.29 or higher. And use a manifest like https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/

devspace open wil not continue

**Comment by digibeuk** [comment]
this has not been released @lizardruss could you make a new release? we need this is our organization thanks!
