### ISSUE TITLE
Constantly downloading devspace

### ISSUE THREAD

**Issue by strowk** [devspace-sh/devspace#2882]
**What happened?**  

Every time I run any devspace command, even `--help`, it starts downloading .. "Download DevSpace CLI release:", which takes several seconds and is very annoying.

**What did you expect to happen instead?**  

Download it only once and reuse.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Just install it on Windows, I suppose, and then run `devspace --init` several times.

**Local Environment:**  
- DevSpace Version: 6.3.12
- Operating System: windows
- ARCH of the OS: AMD64

**Anything else we need to know?**  

I have node and npm installed by fnm and had to add that installation in PATH manually  ( see workaround in https://github.com/devspace-sh/devspace/issues/2881 ). This might somehow interfere?

**Comment by lizardruss** [comment]
@strowk

Are you installing devspace using `npm install -g devspace`? I suspect that the [node install script](https://github.com/devspace-sh/devspace/blob/main/dist/npm/index.js) + the usage of `fnm` is causing this.

I'd recommend using one of the other install methods for now.
