### ISSUE TITLE
Devspace ui fails for v6.3.13

### ISSUE THREAD

**Issue by weg-da** [devspace-sh/devspace#2899]
**What happened?**  
I ran "devspace ui" from cli.
In cli everything as expected:

```
info Using namespace 'test-namespace'
info Using kube context 'minikube'
info Start listening on http://localhost:8090
```
When I open  http://localhost:8090 in the browser (chrome) nothing is presented. In the Chrome Dev Tools console this error is shown:

```
 index.tsx:6 Uncaught TypeError: o.render is not a function
    at Module.<anonymous> (index.tsx:6:1)
    at i (bootstrap:19:22)
    at Object.<anonymous> (main.a9eb55d6.js:1:298982)
    at i (bootstrap:19:22)
    at bootstrap:83:10
    at main.a9eb55d6.js:1:913
```

**What did you expect to happen instead?**  
Devspace ui opens in the browser.

**How can we reproduce the bug?** 
install devspace version 6.3.13
run in cli: devspace ui and open link with browser

**Local Environment:**  
- DevSpace Version: 6.3.13
- Operating System: windows | WSL 

**Current Fix**
use Devspace version: 6.3.12

**Comment by CKnoppas** [comment]
i can confirm this bug. browser shows the same error message as mentioned by @weg-da .

**Comment by nethi** [comment]
Facing the same issue here.

**Comment by abhishekhugetech** [comment]
I had the same issue changed version to `6.3.4` from latest and it's working

```
curl -L -o devspace 'https://github.com/loft-sh/devspace/releases/download/v6.3.4/devspace-linux-arm64' 
```
