### ISSUE TITLE
Use install over upgrade --install when deploying charts for the first time

### ISSUE THREAD

**Issue by pierre-vanliefland-asl** [devspace-sh/devspace#2913]
**Is your feature request related to a problem?**  

When deploying a Chart that comes with CRDs, such as the [Strimzi Kafka Operator chart](https://strimzi.io/), the Kafka CRDs are not installed. 

IIUC, it is because devspace always uses `helm upgrade --install` when deploying a helm chart - and Helm [does not support CRDs when upgrading](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations).

**Which solution do you suggest?**  

Would it be an option to detected whether the chart is already installed or not, and use `install` or `upgrade` accordingly?

**Which alternative solutions exist?**  

If it is not feasible, documenting the current behaviour and the CRDs caveat would be useful.

**Additional context**  

Nope

**Comment by zerbitx** [comment]
The documentation you linked is specifying `--dry-run` as supporting CRDs.  Could you share your output so we can try to reproduce this?  Thank you.

**Comment by pierre-vanliefland-asl** [comment]
@zerbitx sorry, I double-check what was happening and this is a non-issue.

`helm upgrade --install` will trigger the creation of CRDs if the operation is an install. 

The issue that we deployed everything at the same time in our devspace setup (the 3rd-party chart that includes the CRDs and our chart that uses them).

Using the devspace dependencies features properly resolved the issue.
