### ISSUE TITLE
Question: reverse port forwarding to LAN

### ISSUE THREAD

**Issue by jampy** [devspace-sh/devspace#2915]
Is it possitble to set up [reverse port forwarding](https://www.devspace.sh/docs/configuration/dev/connections/port-forwarding#reverse-port-forwarding) to a host on the **local network** (instead of localhost)?

I'd like to connect to SCP-copy files from the dev container to a local Raspberry Pi (that listens on a private IP addres).

I guess I could set up another port-forwarder locally (`dev-container` ----devspace----> `local machine` ----other forwarder----> `raspberry pi`) but I'm wondering if there is an easier way.

---

PS: awesome work! Much prefer devspace to Okteto!
PPS: The `chat with us` links on the devspace.sh website don't seem to work.

**Comment by lizardruss** [comment]
I think setting up a local port-forwarder might be the best option at the moment. You can override the [default dev pipeline](https://www.devspace.sh/docs/configuration/pipelines/#dev) with the commands needed to setup & teardown the local port-forwarder to integrate with the usual DevSpace workflow.
