### ISSUE TITLE
Declarative config for context/namespace

### ISSUE THREAD

**Issue by slavaGanzin** [devspace-sh/devspace#2918]
Hello. 
Awesome project, thanks for your work!

I've read this: https://www.devspace.sh/docs/configuration/variables, but still don't get how can I set which namespace/context I want to use per project. Yeah I can use direnv or something like that to setup ${DEVSPACE_CONTEXT} and ${DEVSPACE_NAMESPACE}, so when I'll switch to a folder it will automatically launch it in a needed context. But that's look like a hack.

**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
I think adding context: and namespace: root config options to devspace.yaml would be the most straightforward. You can override this setting per container in every imaginable place: in image, in deployment, etc. And that's great flexibility. But there is no way to set default value for whole devspace file.

**Which alternative solutions exist?**  
1. direnv
2. additional step in dev pipeline (using this right now)
3. setting vars (kinda works, but still asks about switching to context before running):
```
vars:
  DEVSPACE_NAMESPACE: 
    default: namespacename
  DEVSPACE_CONTEXT: 
    default: contextname
```

**Comment by deniseschannon** [comment]
Thanks for your feedback. We recommend using these commands for what you're trying to achieve. <br><br>[https://www.devspace.sh/docs/cli/devspace_use_context](https://www.devspace.sh/docs/cli/devspace_use_context)<br>[https://www.devspace.sh/docs/cli/devspace_use_namespace](https://www.devspace.sh/docs/cli/devspace_use_namespace)
