### ISSUE TITLE
`hooks[].command` should be equivalent to `commands[].command`

### ISSUE THREAD

**Issue by LukasGentele** [devspace-sh/devspace#730]
**Is your feature request related to a problem?**
Currently, `commands[].command` allows a string with bash-like syntax that is interpreted like a shell script. `hooks[].command`, however, expects a single binary and allows to provide args via `hooks[].args`. This is not intuitive to understand.

**Which solution do you suggest?**
`hooks[].command` should be equivalent to `commands[].command` and expect a command and `hooks[].args` should be deprecated. If `hooks[].args` is specified, there could be a fallback to the current behavior which prevents a breaking change but allows `hooks[].command` to adapt the new behavior.

**Which alternative solutions exist?**

**Additional context**

/kind feature

**Comment by mgruener** [comment]
Why not allow for both variants? Add ```commands[].args```. If it is present, treat ```commands[].command``` as single binary and call it with the args in ```commands[].args``` and if ```commands[].args``` is absent, interpret ```commands[].command``` as shell script. Same for ```hooks[]```.

If that gets too complex, I would prefer keeping the ```.args``` variant and adding it to ```commands[]```, as this is more readable for commands / hooks with more than a few parameters.

**Comment by LukasGentele** [comment]
@mgruener That sounds like a smart way of allowing both. Should be straight forward to implement: `if len(args) == 0 { run command in shell } else { run command using args (no shell interpretation) }`

@FabianKramm What do you think?

**Comment by FabianKramm** [comment]
Yes sounds good to me

**Comment by shaunc** [comment]
As a variant of what @LukasGentele suggests, it could be done using docker's convention: if command is a list, then interpret as binary w/ arguments; if it is a string, then treat it as something to be run in a shell.
