### ISSUE TITLE
awareness for `Dockerfile.dockerignore` files

### ISSUE THREAD

**Issue by LukasGentele** [devspace-sh/devspace#860]
**Is your feature request related to a problem?**
"DevSpace should use the current docker behavior for dockerignore:
Dockerfile  + .dockerignore
Dockerfile + Dockerfile.dockerignore
Dockerfile.frontend + Dockerfile.frontend.dockerignore
"

**Which solution do you suggest?**
Delegating the dockerignore file search to Docker if possible, otherwise copying the behavior as best as possible.

**Which alternative solutions exist?**

**Additional context**

Credits to @korbin for suggesting this via Slack.

/kind feature

**Comment by Qeeq777** [comment]
https://www.qeeq.com/a/mcs18596
--

**Comment by Jahanaraart03** [comment]
nice
https://bit.ly/2SI9WR1

**Comment by camelcrush1979** [comment]
![62C7784C-F5D1-4717-93B3-552E31808AD7](https://user-imag#1091 s.githubusercontent.com/65050497/81460327-e353da00-9161-11ea-9a5a-29a1e332a6c6.png)
#
