### ISSUE TITLE
deployment to given namespace in resource file yaml

### ISSUE THREAD

**Issue by BLoeT** [devspace-sh/devspace#909]
**What happened?**
**devspace.yaml:**
...
deployments:

* name: coredns
  kubectl:
  manifests:
  * coredns/coredns-cm.yaml
    flags:
    * "--namespace"
    * "kube-system"
      ...

**coredns-cm.yaml:**
apiVersion: v1
data:
Corefile: |
.:53 {
..........
}
kind: ConfigMap
metadata:
name: coredns
namespace: kube-system

Terminal command:
devspace deploy --skip-build

Error Message:
the namespace from the provided object "default" does not match the namespace "kube-system". You must pass '--namespace=default' to perform this operation.

**What did you expect to happen instead?**
Should work like
kubectl apply -f coredns/coredns-cm.yaml --namespace=kube-system
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
configmap/coredns configured

This should deploy configmap to given namespace in CM.

Even the flags in devspace.yaml or --namespace in apply command should be for that matter useless, because of given tag namespace in metadata part.

Like this:
kubectl apply -f coredns/coredns-cm.yaml
configmap/coredns unchanged

**How can we reproduce the bug?** (as minimally and precisely as possible)
use configparts from above

**Local Environment:**

* Operating System: mac
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Cloud Provider: other ( docker-desktop )
* Kubernetes Version:
  Client Version: [version.Info](http://version.Info){Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: [version.Info](http://version.Info){Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**
i need to deploy to different namespaces like kube-system, default and custom namespace in one devspace.yaml

/kind bug

**Comment by benjamin658** [comment]
I have the same issue here, currently I used commands as workaround:

```yaml
commands:
- name: deploy
  command: "kubectl apply -f coredns/coredns-cm.yaml  && devspace deploy --skip-build"
```

**Comment by benjamin658** [comment]
Just append a namespace under coredns deployment.

```
- name: coredns
   kubectl:
     manifests:
     - coredns/coredns-cm.yaml
   namespace: kube-system
```

**Comment by FabianKramm** [comment]
@BLoeT thanks for opening this issue! DevSpace already uses the `--namespace` flag, so it will have no effect. You have to specify the namespace in the deployment as @benjamin658 pointed out.

**Comment by BLoeT** [comment]
I thought this is like in the docs described:

> deployments:
> - name: backend
>   kubectl:
>     manifests:
>     - backend/
> 
> The above example will be executing during the deployment process as follows:
> kubectl apply -f backend

so metadata.namespace would be enough.

Thank you very much for pointing this out @benjamin658 and @FabianKramm.

Maybe this should be in the docs.

**Comment by FabianKramm** [comment]
@BLoeT no currently we always add the `--namespace`, but we could think about skipping that if no namespace is defined via `devspace dev --namespace` or in the `deployment[*].namespace`
