### ISSUE TITLE
pipelineerr: sync high cpu usage

### ISSUE THREAD

**Issue by chasebolt** [devspace-sh/devspace#910]
**What happened?**
sync, inside of the container, consistently shows high cpu usage (30-50%) in both minikube and managed DOKS. `.devspace/logs/sync.log` shows no file activity.

**What did you expect to happen instead?**
low cpu usage with no file activity

**How can we reproduce the bug?** (as minimally and precisely as possible)
laravel php project with \~10k files.

**Local Environment:**

* Operating System: linux - ext4
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: digitalocean
* Kubernetes Version: 1.15.5

**Anything else we need to know?**
n/a

/kind bug

**Comment by FabianKramm** [comment]
@chasebolt thanks for opening this issue! The sync in the container currently uses a polling technique to watch for file changes remotely (to support as many filesystems as possible), which can lead to increased cpu usage within a container if a lot of files have to be watched constantly. We could introduce an option where you can specify the poll interval or we could increase it automatically, if there wasn't a file change for some period of time, which would save some cpu cycles.

**Comment by chasebolt** [comment]
ok this makes perfect sense then. i assumed it used inotify with polling as a fallback. thanks.

**Comment by chasebolt** [comment]
for the developer experience i wouldn't want to increase the sync time and will just bear down with the cpu usage until an inotify implementation is available. 👍

**Comment by igoooor** [comment]
Indeed if we could have an option to define the interval for local to container and one for container to local, I think that would be the best.
In my case, syncing back from the container to the local machine could be largely spaced out.

**Comment by LukasGentele** [comment]
@igoooor a config option for the polling time interval for within the container is a good suggestion, I think. For local changes, we use file watchers anyways, so a polling interval is not required.

**Comment by carlmontanari** [comment]
going to close this out as I think it is quite old at this time, but feel free to reopen, or probably better yet open a new issue if this is still a problem in modern devspace!
