### ISSUE TITLE
devspace sync --all option

### ISSUE THREAD

**Issue by igoooor** [devspace-sh/devspace#936]
**Is your feature request related to a problem?**
Not related to a problem

**Which solution do you suggest?**
When using `devspace sync --config some/devspace.yml` if you have multiple sync defined in your file, `devspace sync` will ask you which sync you want to start.
Having an option `--all` to start all sync at the same time with the same one command would be great :)
It would start all syncs, just like they would all be started when you simply run `devspace dev`

/kind feature

**Comment by FabianKramm** [comment]
@igoooor yes I think that is a good idea. Implementation shouldn't be too hard since the functionality is basically already there.

**Comment by igoooor** [comment]
Cool! can't wait for it :D

**Comment by JParkinson1991** [comment]
+1 on this

Currently having to run 4 different session and running each sync manually via command arguments. Would be great if we could just put all this into the devspace config file and forgot about it!

**Comment by igoooor** [comment]
@JParkinson1991 As a workaround I use the command `dev --skip-pipeline` which according to the help does `Skips build & deployment and only starts sync, portforwarding & terminal` which is what we want. Not straightforward, but it works ;)
